services :
  frontend :
    container_name : azuracast_frontend
    build :
      context : .
    user : "${AZURACAST_PUID:-1000}:${AZURACAST_PGID:-1000}"
    volumes :
      - ${LOCAL_WORKSPACE_FOLDER:-..}/frontend:/data/frontend
      - ${LOCAL_WORKSPACE_FOLDER:-..}/resources/locale:/data/resources/locale
      - ${LOCAL_WORKSPACE_FOLDER:-..}/web/static:/data/web/static
      - frontend_node_modules:/data/frontend/node_modules

volumes :
  frontend_node_modules : { }
